from __future__ import annotations

from enum import Enum


class DataPipePhase(str, Enum):
    IDLE = "IDLE"
    HEADERS_PROPOSED_WAITING_CONFIRM = "HEADERS_PROPOSED_WAITING_CONFIRM"
    TRANSFORM_PROPOSED_WAITING_CONFIRM = "TRANSFORM_PROPOSED_WAITING_CONFIRM"
    READY_TO_SAVE_WAITING_CONFIRM = "READY_TO_SAVE_WAITING_CONFIRM"
    DONE = "DONE"
